import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const DEFAULT_EXERCISES = [
  // CHEST
  {
    name: "Barbell Bench Press",
    slug: "barbell-bench-press",
    category: "Barbell",
    primaryMuscle: "Chest",
    secondaryMuscles: "Triceps, Shoulders",
    equipment: "Barbell, Flat Bench",
    instructions: "Lie flat on the bench, grip barbell slightly wider than shoulder width, lower bar to mid-chest, and press explosively up.",
  },
  {
    name: "Incline Dumbbell Press",
    slug: "incline-dumbbell-press",
    category: "Dumbbell",
    primaryMuscle: "Chest",
    secondaryMuscles: "Shoulders, Triceps",
    equipment: "Dumbbells, Incline Bench",
    instructions: "Set bench to 30-45 degrees. Press dumbbells upwards while squeezing the upper chest at peak contraction.",
  },
  {
    name: "Decline Barbell Bench Press",
    slug: "decline-barbell-bench-press",
    category: "Barbell",
    primaryMuscle: "Chest",
    secondaryMuscles: "Triceps",
    equipment: "Barbell, Decline Bench",
    instructions: "Lie on decline bench, lower bar controlled towards lower chest, and press up.",
  },
  {
    name: "Dumbbell Chest Flyes",
    slug: "dumbbell-chest-flyes",
    category: "Dumbbell",
    primaryMuscle: "Chest",
    secondaryMuscles: "Shoulders",
    equipment: "Dumbbells, Flat Bench",
    instructions: "Lie on flat bench, slight bend in elbows, arc weights out wide to feel deep chest stretch, then bring them back together.",
  },
  {
    name: "Cable Crossover",
    slug: "cable-crossover",
    category: "Cable",
    primaryMuscle: "Chest",
    secondaryMuscles: "Shoulders",
    equipment: "Cable Machine",
    instructions: "Stand in center of cable pulleys, pull handles forward and down in an arc, squeezing pecs.",
  },
  {
    name: "Dips (Chest Focus)",
    slug: "dips-chest-focus",
    category: "Bodyweight",
    primaryMuscle: "Chest",
    secondaryMuscles: "Triceps, Shoulders",
    equipment: "Dip Station",
    instructions: "Lean torso forward slightly, flare elbows moderately, lower body until upper arms are parallel to floor, press back up.",
  },
  {
    name: "Push-ups",
    slug: "push-ups",
    category: "Bodyweight",
    primaryMuscle: "Chest",
    secondaryMuscles: "Triceps, Core",
    equipment: "Bodyweight",
    instructions: "Keep body in rigid plank line, lower chest to floor, push back up locking arms softly.",
  },

  // BACK
  {
    name: "Conventional Deadlift",
    slug: "conventional-deadlift",
    category: "Barbell",
    primaryMuscle: "Back",
    secondaryMuscles: "Hamstrings, Glutes, Core",
    equipment: "Barbell",
    instructions: "Stand midfoot under bar, hinge hips to grip bar, brace core, drive through the floor to stand upright.",
  },
  {
    name: "Barbell Bent-Over Row",
    slug: "barbell-bent-over-row",
    category: "Barbell",
    primaryMuscle: "Back",
    secondaryMuscles: "Biceps, Shoulders",
    equipment: "Barbell",
    instructions: "Hinge at hips with torso near 45 degrees, pull barbell to lower chest/upper abdomen, squeezing shoulder blades together.",
  },
  {
    name: "Lat Pulldown",
    slug: "lat-pulldown",
    category: "Cable",
    primaryMuscle: "Back",
    secondaryMuscles: "Biceps",
    equipment: "Lat Pulldown Machine",
    instructions: "Grip wide overhand, pull bar down towards upper chest while leaning slightly back, control return.",
  },
  {
    name: "Seated Cable Row",
    slug: "seated-cable-row",
    category: "Cable",
    primaryMuscle: "Back",
    secondaryMuscles: "Biceps, Core",
    equipment: "Cable Row Machine",
    instructions: "Sit upright, pull handle towards abdomen, retracting scapulae and driving elbows back.",
  },
  {
    name: "Pull-ups",
    slug: "pull-ups",
    category: "Bodyweight",
    primaryMuscle: "Back",
    secondaryMuscles: "Biceps, Forearms",
    equipment: "Pull-up Bar",
    instructions: "Pronated overhand grip wider than shoulders, pull body up until chin clears the bar.",
  },
  {
    name: "Chin-ups",
    slug: "chin-ups",
    category: "Bodyweight",
    primaryMuscle: "Back",
    secondaryMuscles: "Biceps",
    equipment: "Pull-up Bar",
    instructions: "Supinated underhand grip shoulder-width apart, pull body up until chin is over the bar.",
  },
  {
    name: "Single-Arm Dumbbell Row",
    slug: "single-arm-dumbbell-row",
    category: "Dumbbell",
    primaryMuscle: "Back",
    secondaryMuscles: "Biceps",
    equipment: "Dumbbell, Bench",
    instructions: "Support one knee and hand on bench, pull dumbbell with opposite arm upwards towards hip.",
  },
  {
    name: "T-Bar Row",
    slug: "t-bar-row",
    category: "Machine",
    primaryMuscle: "Back",
    secondaryMuscles: "Biceps",
    equipment: "T-Bar Station / Landmine",
    instructions: "Straddle bar, keep spine neutral, row weight into chest cavity with elbows tucked.",
  },
  {
    name: "Face Pull",
    slug: "face-pull",
    category: "Cable",
    primaryMuscle: "Shoulders",
    secondaryMuscles: "Upper Back, Rotator Cuff",
    equipment: "Cable Machine, Rope",
    instructions: "Set rope at eye level, pull towards face while rotating hands back, squeezing rear deltoids.",
  },

  // SHOULDERS
  {
    name: "Overhead Barbell Press (OHP)",
    slug: "overhead-barbell-press",
    category: "Barbell",
    primaryMuscle: "Shoulders",
    secondaryMuscles: "Triceps, Core",
    equipment: "Barbell",
    instructions: "Stand tall, barbell resting on clavicle, press straight overhead locking elbows, head clears bar.",
  },
  {
    name: "Seated Dumbbell Shoulder Press",
    slug: "seated-dumbbell-shoulder-press",
    category: "Dumbbell",
    primaryMuscle: "Shoulders",
    secondaryMuscles: "Triceps",
    equipment: "Dumbbells, 90-deg Bench",
    instructions: "Sit with back supported, press dumbbells vertically overhead, slowly descend to ear height.",
  },
  {
    name: "Dumbbell Lateral Raise",
    slug: "dumbbell-lateral-raise",
    category: "Dumbbell",
    primaryMuscle: "Shoulders",
    secondaryMuscles: "Traps",
    equipment: "Dumbbells",
    instructions: "Stand upright, raise dumbbells laterally to shoulder level with slight lead from elbows.",
  },
  {
    name: "Cable Lateral Raise",
    slug: "cable-lateral-raise",
    category: "Cable",
    primaryMuscle: "Shoulders",
    secondaryMuscles: "Traps",
    equipment: "Cable Machine",
    instructions: "Low pulley cable, sweep handle outwards away from body for constant tension across lateral delt.",
  },
  {
    name: "Arnold Press",
    slug: "arnold-press",
    category: "Dumbbell",
    primaryMuscle: "Shoulders",
    secondaryMuscles: "Triceps",
    equipment: "Dumbbells, Bench",
    instructions: "Start with palms facing chest, rotate outwards as you press overhead until palms face forward.",
  },
  {
    name: "Reverse Pec Deck Fly",
    slug: "reverse-pec-deck-fly",
    category: "Machine",
    primaryMuscle: "Shoulders",
    secondaryMuscles: "Upper Back",
    equipment: "Pec Deck Machine",
    instructions: "Sit facing machine pad, pull handles back horizontally targeting posterior deltoids.",
  },
  {
    name: "Dumbbell Front Raise",
    slug: "dumbbell-front-raise",
    category: "Dumbbell",
    primaryMuscle: "Shoulders",
    secondaryMuscles: "Chest",
    equipment: "Dumbbells",
    instructions: "Raise weights straight in front of you until parallel to the floor.",
  },

  // LEGS
  {
    name: "Barbell Back Squat",
    slug: "barbell-back-squat",
    category: "Barbell",
    primaryMuscle: "Quads",
    secondaryMuscles: "Glutes, Hamstrings, Core",
    equipment: "Barbell, Squat Rack",
    instructions: "Rest bar on upper traps, descend until hip crease is below knee, press back up through whole foot.",
  },
  {
    name: "Front Squat",
    slug: "front-squat",
    category: "Barbell",
    primaryMuscle: "Quads",
    secondaryMuscles: "Core, Glutes",
    equipment: "Barbell, Squat Rack",
    instructions: "Clean grip or cross arm, bar rests across anterior deltoids, keep torso upright while squatting deep.",
  },
  {
    name: "Romanian Deadlift (RDL)",
    slug: "romanian-deadlift",
    category: "Barbell",
    primaryMuscle: "Hamstrings",
    secondaryMuscles: "Glutes, Lower Back",
    equipment: "Barbell or Dumbbells",
    instructions: "Soft bend in knees, hinge hips backwards keeping back flat until hamstrings are stretched, drive hips forward.",
  },
  {
    name: "Leg Press",
    slug: "leg-press",
    category: "Machine",
    primaryMuscle: "Quads",
    secondaryMuscles: "Glutes",
    equipment: "Leg Press Machine",
    instructions: "Feet shoulder-width on carriage platform, lower sled smoothly to 90 degrees knee bend, press back up.",
  },
  {
    name: "Bulgarian Split Squat",
    slug: "bulgarian-split-squat",
    category: "Dumbbell",
    primaryMuscle: "Quads",
    secondaryMuscles: "Glutes, Hamstrings",
    equipment: "Dumbbells, Flat Bench",
    instructions: "One foot elevated behind on bench, lunge down on front leg until back knee almost touches ground.",
  },
  {
    name: "Leg Extension",
    slug: "leg-extension",
    category: "Machine",
    primaryMuscle: "Quads",
    secondaryMuscles: "None",
    equipment: "Leg Extension Machine",
    instructions: "Sit back in machine, extend legs forward until quads are contracted, pause and lower under control.",
  },
  {
    name: "Lying Leg Curl",
    slug: "lying-leg-curl",
    category: "Machine",
    primaryMuscle: "Hamstrings",
    secondaryMuscles: "Calves",
    equipment: "Lying Leg Curl Machine",
    instructions: "Lie prone, curl pad towards glutes squeezing hamstrings tightly, resist slowly on the descent.",
  },
  {
    name: "Barbell Hip Thrust",
    slug: "barbell-hip-thrust",
    category: "Barbell",
    primaryMuscle: "Glutes",
    secondaryMuscles: "Hamstrings",
    equipment: "Barbell, Bench, Pad",
    instructions: "Upper back against bench, barbell across hips, drive hips towards ceiling until thighs and torso align.",
  },
  {
    name: "Standing Calf Raise",
    slug: "standing-calf-raise",
    category: "Machine",
    primaryMuscle: "Calves",
    secondaryMuscles: "None",
    equipment: "Calf Raise Machine",
    instructions: "Balls of feet on platform edge, lower heels for deep calf stretch, push up onto tiptoes.",
  },
  {
    name: "Seated Calf Raise",
    slug: "seated-calf-raise",
    category: "Machine",
    primaryMuscle: "Calves",
    secondaryMuscles: "None",
    equipment: "Seated Calf Machine",
    instructions: "Knees pinned under pad, focus on soleus muscle contraction at peak elevation.",
  },
  {
    name: "Walking Lunges",
    slug: "walking-lunges",
    category: "Dumbbell",
    primaryMuscle: "Quads",
    secondaryMuscles: "Glutes, Hamstrings",
    equipment: "Dumbbells or Bodyweight",
    instructions: "Step forward into deep lunge, back knee skimming floor, drive forward onto the lead foot into next stride.",
  },

  // ARMS (BICEPS & TRICEPS)
  {
    name: "Barbell Bicep Curl",
    slug: "barbell-bicep-curl",
    category: "Barbell",
    primaryMuscle: "Biceps",
    secondaryMuscles: "Forearms",
    equipment: "Barbell or EZ-Bar",
    instructions: "Keep elbows pinned to sides, curl barbell up towards shoulders, avoiding body sway.",
  },
  {
    name: "Incline Dumbbell Curl",
    slug: "incline-dumbbell-curl",
    category: "Dumbbell",
    primaryMuscle: "Biceps",
    secondaryMuscles: "Forearms",
    equipment: "Dumbbells, Incline Bench",
    instructions: "Lie back at 45 degree angle for deep bicep stretch, curl weights up supinating wrists.",
  },
  {
    name: "Hammer Curl",
    slug: "hammer-curl",
    category: "Dumbbell",
    primaryMuscle: "Biceps",
    secondaryMuscles: "Brachialis, Forearms",
    equipment: "Dumbbells",
    instructions: "Neutral palms-in grip, curl dumbbells upward maintaining neutral wrist alignment.",
  },
  {
    name: "Preacher Curl",
    slug: "preacher-curl",
    category: "Machine",
    primaryMuscle: "Biceps",
    secondaryMuscles: "Forearms",
    equipment: "Preacher Bench, EZ-Bar",
    instructions: "Rest upper arms flat on slanted pad, curl bar up emphasizing strict isolated bicep contraction.",
  },
  {
    name: "Tricep Rope Pushdown",
    slug: "tricep-rope-pushdown",
    category: "Cable",
    primaryMuscle: "Triceps",
    secondaryMuscles: "Forearms",
    equipment: "Cable Machine, Rope",
    instructions: "Elbows pinned to ribs, push rope down and spread handles outward at the bottom for full lockout.",
  },
  {
    name: "Skull Crushers (Lying Tricep Ext)",
    slug: "skull-crushers",
    category: "Barbell",
    primaryMuscle: "Triceps",
    secondaryMuscles: "Shoulders",
    equipment: "EZ-Bar, Flat Bench",
    instructions: "Lie on bench, lower bar smoothly towards forehead or crown of head, hinge at elbows to press up.",
  },
  {
    name: "Overhead Dumbbell Tricep Extension",
    slug: "overhead-dumbbell-tricep-ext",
    category: "Dumbbell",
    primaryMuscle: "Triceps",
    secondaryMuscles: "Shoulders",
    equipment: "Dumbbell",
    instructions: "Hold dumbbell with both hands overhead, lower behind head until forearms pass 90 degrees, press up.",
  },
  {
    name: "Close-Grip Bench Press",
    slug: "close-grip-bench-press",
    category: "Barbell",
    primaryMuscle: "Triceps",
    secondaryMuscles: "Chest, Shoulders",
    equipment: "Barbell, Flat Bench",
    instructions: "Hands shoulder-width apart, keep elbows tucked close to ribcage while lowering and pressing.",
  },

  // CORE
  {
    name: "Hanging Leg Raise",
    slug: "hanging-leg-raise",
    category: "Bodyweight",
    primaryMuscle: "Core",
    secondaryMuscles: "Hip Flexors, Grip",
    equipment: "Pull-up Bar",
    instructions: "Hang from bar without swinging, raise toes up to horizontal or towards bar, lower controlled.",
  },
  {
    name: "Ab Wheel Rollout",
    slug: "ab-wheel-rollout",
    category: "Bodyweight",
    primaryMuscle: "Core",
    secondaryMuscles: "Lats, Shoulders",
    equipment: "Ab Roller Wheel",
    instructions: "Kneel on floor, roll wheel forward while maintaining hollow body core brace, pull back using abs.",
  },
  {
    name: "Plank",
    slug: "plank",
    category: "Bodyweight",
    primaryMuscle: "Core",
    secondaryMuscles: "Shoulders, Glutes",
    equipment: "Mat",
    instructions: "Hold rigid horizontal posture on forearms and toes, squeezing glutes and abdomen tightly.",
  },
  {
    name: "Cable Woodchopper",
    slug: "cable-woodchopper",
    category: "Cable",
    primaryMuscle: "Core",
    secondaryMuscles: "Obliques, Shoulders",
    equipment: "Cable Machine",
    instructions: "Diagonal rotation pulling cable handle across body using obliques and core rotation.",
  },
  {
    name: "Russian Twists",
    slug: "russian-twists",
    category: "Bodyweight",
    primaryMuscle: "Core",
    secondaryMuscles: "Obliques",
    equipment: "Mat / Weight Plate",
    instructions: "Sit on floor with knees bent and feet elevated, rotate torso side-to-side touching floor.",
  },

  // --- SMITH MACHINE EXERCISES ---
  {
    name: "Smith Machine Flat Bench Press",
    slug: "smith-machine-flat-bench-press",
    category: "Smith Machine",
    primaryMuscle: "Chest",
    secondaryMuscles: "Triceps, Shoulders",
    equipment: "Smith Machine, Flat Bench",
    instructions: "Position bench under bar, lower bar with controlled fixed path to mid chest, press upwards smoothly.",
  },
  {
    name: "Smith Machine Incline Bench Press",
    slug: "smith-machine-incline-bench-press",
    category: "Smith Machine",
    primaryMuscle: "Chest",
    secondaryMuscles: "Shoulders, Triceps",
    equipment: "Smith Machine, Incline Bench",
    instructions: "Set incline bench to 30 degrees, unrack bar and lower to upper clavicle area, press to lockout.",
  },
  {
    name: "Smith Machine Decline Bench Press",
    slug: "smith-machine-decline-bench-press",
    category: "Smith Machine",
    primaryMuscle: "Chest",
    secondaryMuscles: "Triceps",
    equipment: "Smith Machine, Decline Bench",
    instructions: "Lie on decline bench, lower bar smoothly to lower pec line, drive upwards.",
  },
  {
    name: "Smith Machine Squat",
    slug: "smith-machine-squat",
    category: "Smith Machine",
    primaryMuscle: "Quads",
    secondaryMuscles: "Glutes, Hamstrings",
    equipment: "Smith Machine",
    instructions: "Feet placed slightly forward to emphasize quad loading, descend to parallel or deeper, drive through feet.",
  },
  {
    name: "Smith Machine Bulgarian Split Squat",
    slug: "smith-machine-bulgarian-split-squat",
    category: "Smith Machine",
    primaryMuscle: "Quads",
    secondaryMuscles: "Glutes, Hamstrings",
    equipment: "Smith Machine, Flat Bench",
    instructions: "Rear foot on bench, front foot forward, squat down along the fixed guide rails with extreme quad isolation.",
  },
  {
    name: "Smith Machine Romanian Deadlift (RDL)",
    slug: "smith-machine-romanian-deadlift",
    category: "Smith Machine",
    primaryMuscle: "Hamstrings",
    secondaryMuscles: "Glutes, Lower Back",
    equipment: "Smith Machine",
    instructions: "Hinge hips backward along the vertical track, feeling hamstring tension, drive hips through to top.",
  },
  {
    name: "Smith Machine Hip Thrust",
    slug: "smith-machine-hip-thrust",
    category: "Smith Machine",
    primaryMuscle: "Glutes",
    secondaryMuscles: "Hamstrings",
    equipment: "Smith Machine, Bench, Pad",
    instructions: "Upper back on bench, bar with pad over hip crease, drive hips up to full glute contraction.",
  },
  {
    name: "Smith Machine Overhead Shoulder Press",
    slug: "smith-machine-overhead-shoulder-press",
    category: "Smith Machine",
    primaryMuscle: "Shoulders",
    secondaryMuscles: "Triceps",
    equipment: "Smith Machine, Upright Bench",
    instructions: "Sit upright, press bar vertically overhead from chin height to lockout.",
  },
  {
    name: "Smith Machine Bent-Over Row",
    slug: "smith-machine-bent-over-row",
    category: "Smith Machine",
    primaryMuscle: "Back",
    secondaryMuscles: "Biceps",
    equipment: "Smith Machine",
    instructions: "Hinge torso at 45 degrees, pull bar towards belly button along the smooth track.",
  },
  {
    name: "Smith Machine Shrugs",
    slug: "smith-machine-shrugs",
    category: "Smith Machine",
    primaryMuscle: "Back",
    secondaryMuscles: "Traps",
    equipment: "Smith Machine",
    instructions: "Grip bar shoulder-width, elevate shoulders straight up towards ears, pause and lower.",
  },
  {
    name: "Smith Machine Standing Calf Raise",
    slug: "smith-machine-standing-calf-raise",
    category: "Smith Machine",
    primaryMuscle: "Calves",
    secondaryMuscles: "None",
    equipment: "Smith Machine, Step / Block",
    instructions: "Stand on elevated block under bar, lower heels deep for stretch, press onto balls of feet.",
  },
  {
    name: "Smith Machine Close-Grip Bench Press",
    slug: "smith-machine-close-grip-bench-press",
    category: "Smith Machine",
    primaryMuscle: "Triceps",
    secondaryMuscles: "Chest",
    equipment: "Smith Machine, Flat Bench",
    instructions: "Grip shoulder-width, tuck elbows to ribs, press focusing purely on triceps extension.",
  },

  // --- MACHINE EXERCISES ---
  {
    name: "Machine Chest Press",
    slug: "machine-chest-press",
    category: "Machine",
    primaryMuscle: "Chest",
    secondaryMuscles: "Triceps, Shoulders",
    equipment: "Chest Press Machine",
    instructions: "Adjust seat so handles align with mid-chest, press handles forward, control return.",
  },
  {
    name: "Machine Incline Chest Press",
    slug: "machine-incline-chest-press",
    category: "Machine",
    primaryMuscle: "Chest",
    secondaryMuscles: "Shoulders, Triceps",
    equipment: "Incline Chest Machine",
    instructions: "Seat adjusted so handles align with upper clavicle, press upward and inward.",
  },
  {
    name: "Pec Deck (Chest Fly Machine)",
    slug: "pec-deck-chest-fly-machine",
    category: "Machine",
    primaryMuscle: "Chest",
    secondaryMuscles: "Shoulders",
    equipment: "Pec Deck Machine",
    instructions: "Keep slight bend in elbows, squeeze arms together in front of chest, hold peak contraction.",
  },
  {
    name: "Machine Seated Row",
    slug: "machine-seated-row",
    category: "Machine",
    primaryMuscle: "Back",
    secondaryMuscles: "Biceps",
    equipment: "Seated Row Machine",
    instructions: "Chest against pad, pull handles back retracting scapulae, drive elbows behind torso.",
  },
  {
    name: "Machine High Row",
    slug: "machine-high-row",
    category: "Machine",
    primaryMuscle: "Back",
    secondaryMuscles: "Biceps, Lats",
    equipment: "High Row Machine",
    instructions: "Pull downward and backward from high angle towards ribcage, squeeze lats.",
  },
  {
    name: "Assisted Pull-up Machine",
    slug: "assisted-pull-up-machine",
    category: "Machine",
    primaryMuscle: "Back",
    secondaryMuscles: "Biceps",
    equipment: "Assisted Pull-up Station",
    instructions: "Kneel or stand on counterweight pad, pull chin up over handles with strict form.",
  },
  {
    name: "Machine Shoulder Press",
    slug: "machine-shoulder-press",
    category: "Machine",
    primaryMuscle: "Shoulders",
    secondaryMuscles: "Triceps",
    equipment: "Shoulder Press Machine",
    instructions: "Seat adjusted so handles are near ear level, press vertically to full arm extension.",
  },
  {
    name: "Machine Lateral Raise",
    slug: "machine-lateral-raise",
    category: "Machine",
    primaryMuscle: "Shoulders",
    secondaryMuscles: "Traps",
    equipment: "Lateral Raise Machine",
    instructions: "Rest elbows against pads, raise arms laterally to shoulder height with continuous tension.",
  },
  {
    name: "Hack Squat Machine",
    slug: "hack-squat-machine",
    category: "Machine",
    primaryMuscle: "Quads",
    secondaryMuscles: "Glutes",
    equipment: "Hack Squat Machine",
    instructions: "Back flat against pad, feet shoulder width on plate, squat deep for maximum quad stretch.",
  },
  {
    name: "Pendulum Squat Machine",
    slug: "pendulum-squat-machine",
    category: "Machine",
    primaryMuscle: "Quads",
    secondaryMuscles: "Glutes",
    equipment: "Pendulum Squat Machine",
    instructions: "Arcing trajectory takes strain off lower back while loading quadriceps throughout range of motion.",
  },
  {
    name: "V-Squat Machine",
    slug: "v-squat-machine",
    category: "Machine",
    primaryMuscle: "Quads",
    secondaryMuscles: "Glutes, Hamstrings",
    equipment: "V-Squat Machine",
    instructions: "Face-in or face-out setup, squat smooth and deep with supported back and shoulder pads.",
  },
  {
    name: "Seated Leg Extension Machine",
    slug: "seated-leg-extension-machine",
    category: "Machine",
    primaryMuscle: "Quads",
    secondaryMuscles: "None",
    equipment: "Leg Extension Machine",
    instructions: "Align knee joint with machine pivot, extend legs straight forward and squeeze quads.",
  },
  {
    name: "Lying Hamstring Curl Machine",
    slug: "lying-hamstring-curl-machine",
    category: "Machine",
    primaryMuscle: "Hamstrings",
    secondaryMuscles: "Calves",
    equipment: "Lying Leg Curl Machine",
    instructions: "Lie face down, curl pad up toward glutes keeping hips pressed into bench, slow negative.",
  },
  {
    name: "Seated Hamstring Curl Machine",
    slug: "seated-hamstring-curl-machine",
    category: "Machine",
    primaryMuscle: "Hamstrings",
    secondaryMuscles: "Calves",
    equipment: "Seated Leg Curl Machine",
    instructions: "Lap pad pinned snug, curl heels downward and under seat for deep hamstring flexion.",
  },
  {
    name: "Machine Hip Abduction",
    slug: "machine-hip-abduction",
    category: "Machine",
    primaryMuscle: "Glutes",
    secondaryMuscles: "None",
    equipment: "Abductor Machine",
    instructions: "Sit upright, push pads outward away from midline, squeezing upper outer glutes.",
  },
  {
    name: "Machine Hip Adduction",
    slug: "machine-hip-adduction",
    category: "Machine",
    primaryMuscle: "Glutes",
    secondaryMuscles: "Inner Thighs",
    equipment: "Adductor Machine",
    instructions: "Squeeze pads inward towards center, targeting inner thigh and adductor muscles.",
  },
  {
    name: "Machine Preacher Bicep Curl",
    slug: "machine-preacher-bicep-curl",
    category: "Machine",
    primaryMuscle: "Biceps",
    secondaryMuscles: "Forearms",
    equipment: "Preacher Curl Machine",
    instructions: "Triceps flat on pad, curl handles upwards isolating biceps at peak tension.",
  },
  {
    name: "Assisted Dip Machine",
    slug: "assisted-dip-machine",
    category: "Machine",
    primaryMuscle: "Triceps",
    secondaryMuscles: "Chest, Shoulders",
    equipment: "Assisted Dip Machine",
    instructions: "Place knees on support pad, lower until elbows reach 90 degrees, press to lockout.",
  },
  {
    name: "Machine Tricep Dip / Extension",
    slug: "machine-tricep-dip-extension",
    category: "Machine",
    primaryMuscle: "Triceps",
    secondaryMuscles: "Chest",
    equipment: "Seated Dip Machine",
    instructions: "Sit in machine, push handles downward to lock out triceps, resist back up.",
  },
  {
    name: "Abdominal Crunch Machine",
    slug: "abdominal-crunch-machine",
    category: "Machine",
    primaryMuscle: "Core",
    secondaryMuscles: "None",
    equipment: "Ab Crunch Machine",
    instructions: "Hold handles, crunch ribcage down toward pelvis with core contraction.",
  },
  {
    name: "Rotary Torso Machine",
    slug: "rotary-torso-machine",
    category: "Machine",
    primaryMuscle: "Core",
    secondaryMuscles: "Obliques",
    equipment: "Rotary Torso Machine",
    instructions: "Rotate torso against resistance pad from side to side targeting oblique musculature.",
  },
  {
    name: "Captain's Chair Knee/Leg Raise",
    slug: "captains-chair-knee-leg-raise",
    category: "Machine",
    primaryMuscle: "Core",
    secondaryMuscles: "Hip Flexors",
    equipment: "Captain's Chair Tower",
    instructions: "Support body on forearms, lift knees or straight legs up to 90 degrees without swinging.",
  },
  {
    name: "Cable Overhead Tricep Extension",
    slug: "cable-overhead-tricep-extension",
    category: "Cable",
    primaryMuscle: "Triceps",
    secondaryMuscles: "Shoulders",
    equipment: "Cable Machine, Rope",
    instructions: "Face away from high cable, extend rope overhead spreading handles outward at full extension.",
  },
  {
    name: "Cable Bicep Curl",
    slug: "cable-bicep-curl",
    category: "Cable",
    primaryMuscle: "Biceps",
    secondaryMuscles: "Forearms",
    equipment: "Cable Machine, Straight Bar",
    instructions: "Low pulley straight bar, curl upward with continuous tension throughout range.",
  },
  {
    name: "Cable Crunch",
    slug: "cable-crunch",
    category: "Cable",
    primaryMuscle: "Core",
    secondaryMuscles: "None",
    equipment: "Cable Machine, Rope",
    instructions: "Kneel facing cable with rope behind head, flex spine to bring elbows toward thighs.",
  },
];

async function main() {
  console.log("Seeding Gymlo database...");

  // Create default guest user
  const user = await prisma.user.upsert({
    where: { id: "guest-user" },
    update: {},
    create: {
      id: "guest-user",
      name: "Gymlo Athlete",
      email: "athlete@gymlo.app",
    },
  });
  console.log(`Default user ready: ${user.name}`);

  // Upsert exercises
  const exerciseMap: Record<string, string> = {};
  for (const ex of DEFAULT_EXERCISES) {
    const created = await prisma.exercise.upsert({
      where: { slug: ex.slug },
      update: {
        category: ex.category,
        primaryMuscle: ex.primaryMuscle,
        secondaryMuscles: ex.secondaryMuscles,
        equipment: ex.equipment,
        instructions: ex.instructions,
      },
      create: {
        name: ex.name,
        slug: ex.slug,
        category: ex.category,
        primaryMuscle: ex.primaryMuscle,
        secondaryMuscles: ex.secondaryMuscles,
        equipment: ex.equipment,
        instructions: ex.instructions,
        isCustom: false,
      },
    });
    exerciseMap[ex.slug] = created.id;
  }
  console.log(`Seeded ${DEFAULT_EXERCISES.length} exercises.`);

  // Create standard starter routines
  const pushRoutine = await prisma.routine.upsert({
    where: { id: "routine-push-day" },
    update: {},
    create: {
      id: "routine-push-day",
      name: "Push Day (Chest, Shoulders, Triceps)",
      description: "Comprehensive push workout targeting chest pressing, overhead shoulder strength, and triceps hypertrophy.",
      userId: user.id,
      exercises: {
        create: [
          {
            exerciseId: exerciseMap["barbell-bench-press"],
            orderIndex: 0,
            targetSets: 4,
            targetReps: "6-8",
            notes: "Heavy compound, warm up thoroughly",
          },
          {
            exerciseId: exerciseMap["incline-dumbbell-press"],
            orderIndex: 1,
            targetSets: 3,
            targetReps: "8-12",
            notes: "Focus on upper chest contraction",
          },
          {
            exerciseId: exerciseMap["overhead-barbell-press"],
            orderIndex: 2,
            targetSets: 3,
            targetReps: "8-10",
            notes: "Strict form, lock out overhead",
          },
          {
            exerciseId: exerciseMap["dumbbell-lateral-raise"],
            orderIndex: 3,
            targetSets: 4,
            targetReps: "12-15",
            notes: "Slow eccentric",
          },
          {
            exerciseId: exerciseMap["tricep-rope-pushdown"],
            orderIndex: 4,
            targetSets: 3,
            targetReps: "10-12",
            notes: "Spread rope at full extension",
          },
        ],
      },
    },
  });

  const pullRoutine = await prisma.routine.upsert({
    where: { id: "routine-pull-day" },
    update: {},
    create: {
      id: "routine-pull-day",
      name: "Pull Day (Back, Rear Delts, Biceps)",
      description: "Deadlifts, vertical and horizontal rows, rear deltoids, and arm isolation for a complete back workout.",
      userId: user.id,
      exercises: {
        create: [
          {
            exerciseId: exerciseMap["conventional-deadlift"],
            orderIndex: 0,
            targetSets: 3,
            targetReps: "5",
            notes: "Primary posterior chain builder",
          },
          {
            exerciseId: exerciseMap["barbell-bent-over-row"],
            orderIndex: 1,
            targetSets: 4,
            targetReps: "8-10",
            notes: "Control pull to belly button",
          },
          {
            exerciseId: exerciseMap["lat-pulldown"],
            orderIndex: 2,
            targetSets: 3,
            targetReps: "10-12",
            notes: "Full stretch at top",
          },
          {
            exerciseId: exerciseMap["face-pull"],
            orderIndex: 3,
            targetSets: 4,
            targetReps: "15",
            notes: "Posterior shoulder and posture health",
          },
          {
            exerciseId: exerciseMap["barbell-bicep-curl"],
            orderIndex: 4,
            targetSets: 3,
            targetReps: "10-12",
            notes: "No swinging",
          },
        ],
      },
    },
  });

  const legRoutine = await prisma.routine.upsert({
    where: { id: "routine-leg-day" },
    update: {},
    create: {
      id: "routine-leg-day",
      name: "Leg Day (Quads, Hamstrings, Glutes, Calves)",
      description: "Squat-dominant lower body day designed for quad development, posterior chain power, and calves.",
      userId: user.id,
      exercises: {
        create: [
          {
            exerciseId: exerciseMap["barbell-back-squat"],
            orderIndex: 0,
            targetSets: 4,
            targetReps: "6-8",
            notes: "Full depth squatting",
          },
          {
            exerciseId: exerciseMap["romanian-deadlift"],
            orderIndex: 1,
            targetSets: 3,
            targetReps: "8-10",
            notes: "Feel deep stretch in hamstrings",
          },
          {
            exerciseId: exerciseMap["leg-press"],
            orderIndex: 2,
            targetSets: 3,
            targetReps: "10-12",
            notes: "High foot placement for glutes/quads",
          },
          {
            exerciseId: exerciseMap["lying-leg-curl"],
            orderIndex: 3,
            targetSets: 3,
            targetReps: "12-15",
            notes: "Controlled negative",
          },
          {
            exerciseId: exerciseMap["standing-calf-raise"],
            orderIndex: 4,
            targetSets: 4,
            targetReps: "15-20",
            notes: "Pause at full extension",
          },
        ],
      },
    },
  });

  console.log("Routines created:", [pushRoutine.name, pullRoutine.name, legRoutine.name]);
  console.log("Seeding finished successfully!");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
